controllers/CategoriesController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Categories;
use app\models\search\CategoriesSearch;

use yii\web\Controller;
use yii\web\NotFoundHttpException;

use yii\filters\VerbFilter;
use yii\filters\AccessControl;


class CategoriesController extends Controller
{
    //Поведение
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
            'access' =>[
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@'],
                        'matchCallback' => function(){
                            if(!Yii::$app->user->isGuest){
                                return Yii::$app->user->identity->getIsAdmin();
                            }
                            return false;
                        }
                    ],
                ],
            ],
        ];
    }

    //Вывод всех Категорий
    public function actionIndex()
    {
        $searchModel = new CategoriesSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    //Вывод одной категории
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    //Создание
    public function actionCreate()
    {
        $model = new Categories();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['index']);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    //Редактирование
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['index']);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    //Удаление
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    //Поиск модели категорий по их значению ключа
    protected function findModel($id)
    {
        if (($model = Categories::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

controllers/PostsController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Posts;
use app\models\search\PostSearch;

use yii\web\Controller;
use yii\web\ForbiddenHttpException;
use yii\web\NotFoundHttpException;

use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use yii\web\UploadedFile;

class PostsController extends Controller
{
    //поведение
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
            'access' =>[
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
        ];
    }

    //Список всех постов
    public function actionIndex()
    {
        $searchModel = new PostSearch();
        if(!Yii::$app->user->identity->getIsAdmin()) {
            $searchModel->user_id = Yii::$app->user->id;
        };
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    //Отображает одну запись
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    //Создание новой записи
    public function actionCreate()
    {

        $model = new Posts();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            $this->save($model);
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    private function save($model)
    {
        if($model->imageFile = UploadedFile::getInstance($model,'imageFile')){
            if($model->logo){
                @unlink($model->logo);
            }
            $imageName = 'uploads/'.$model->title . '.' . $model->imageFile->extension;
            $model->imageFile->saveAs($imageName );
            $model->logo = $imageName;
            $model->save(false);
        }
    }

    //Редактирование записи.
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            $this->save($model);
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    //Удаление записей
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    //Находит модель записи на основе ее значения первичного ключа.
    protected function findModel($id)
    {
        if (($model = Posts::findOne($id)) !== null) {
            //запрет доступа для пользователей
            if($model->user_id !=Yii::$app->user->id && !Yii::$app->user->identity->getIsAdmin()){
                throw new ForbiddenHttpException(Yii::t('app','Access denied'));
            }
            //запрет доступа для пользователей---
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

controllers/SiteController.php
<?php

namespace app\controllers;

use app\models\Portfolios;
use app\models\Posts;
use app\models\RegForm;
use app\models\search\PostSearch;
use app\models\LoginForm;
use app\models\ContactForm;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\data\ActiveDataProvider;
use yii\web\NotFoundHttpException;

use yii\web\Response;
use yii\widgets\ActiveForm;

class SiteController extends Controller
{
    //поведение
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    //
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    //отображение главной страници
    public function actionIndex()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => Posts::find()->where(['private' => '0']),
            'pagination' => [
                'defaultPageSize' => 5,
                'forcePageParam' => false,
                'pageSizeParam' => false,
            ],
            'sort' => [
                'defaultOrder'=>[
                    'date' => SORT_DESC,
                ],
            ],
        ]);

        return $this->render('index', [
            'dataProvider' => $dataProvider
        ]);
    }

    //страница записи со  слагом
    public function actionView( $slug )
    {
        if(false != ($model = Posts::findOne([
                'slug' => $slug,
                'private' => '0',
            ]))){
            return $this->render('view', [
                'model' => $model,
            ]);
        }else{
            throw new NotFoundHttpException(Yii::t('app','Post not found'));
        }
    }

    //страница портфолио
    public function actionPortfolios()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => Portfolios::find(),
            'pagination' => [
                'defaultPageSize' => 5,
                'forcePageParam' => false,
                'pageSizeParam' => false,
            ],
        ]);

        return $this->render('portfolios', [
                'dataProvider' => $dataProvider

        ]);
    }

    //вывод тегов
    public function actionTag()
    {
        $searchModel = new PostSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams, '');


        return $this->render('index',[
            'searchModel'=>$searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    //вывод категорий
    public function actionCategory()
    {
        return $this->actionTag();
    }

    //страница авторизации
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }
        $this->layout = 'login';

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        }
        return $this->render('login', [
            'model' => $model,
        ]);
    }

    //страница регистрации
    public function actionRegister()
    {
        $this->layout = 'reg';
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new RegForm();

        $this->performAjaxValidation($model);


        if ($model->load(Yii::$app->request->post()) && $model->reg()) {
            return $this->goBack();
        }

        return $this->render('register', [
            'model' => $model ,
        ]);
    }

    //logout
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

   //страница контактов
    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->contact(Yii::$app->params['adminEmail'])) {
            Yii::$app->session->setFlash('contactFormSubmitted');

            return $this->refresh();
        }
        return $this->render('contact', [
            'model' => $model,
        ]);
    }

    //страница about
    public function actionAbout()
    {
        return $this->render('about');
    }

    protected function performAjaxValidation($model)
    {
        if (Yii::$app->request->isAjax && $model->load(Yii::$app->request->post())) {
            Yii::$app->response->format = Response::FORMAT_JSON;
            Yii::$app->response->data   = ActiveForm::validate($model);
            Yii::$app->response->send();
            Yii::$app->end();
        }
    }


}

controllers/TagsController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Tags;
use app\models\search\TagsSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;


class TagsController extends Controller
{
    //Поведение
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
            'access' =>[
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@'],
                        'matchCallback' => function(){ return Yii::$app->user->identity->getIsAdmin();}
                    ],
                ],
            ],
        ];
    }

    //Список всех тегов
    public function actionIndex()
    {
        $searchModel = new TagsSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    //Отображение одного тега
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    //Создание
    public function actionCreate()
    {
        $model = new Tags();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['index']);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    //Редактирование
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['index']);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    //Удаление
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    //Поиск модели тегов по их значению ключа
    protected function findModel($id)
    {
        if (($model = Tags::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

views/layouts/_navbar.php
<?php

use yii\bootstrap\Nav;
use yii\helpers\Html;
use yii\bootstrap\NavBar;

NavBar::begin([
    'brandLabel' => Html::img('/images/logo.png'),
//    'brandUrl' => Yii::$app->homeUrl,
    'options' => [
        'encodeLabels' => false,
        'class' => 'navbar-inverse affix-top',
        'tag' => 'div'
    ],
]);

//Создание массива
$items2 = [];
$items = [
    ['label' => Yii::t('app', 'Home'), 'url' => ['/']]
];
if(Yii::$app->user->isGuest){
    $items[] = ['label' => Yii::t('app', 'Portfolios'), 'url' => ['/site/portfolios']];
    $items2[] = ['label' => Yii::t('app','Log in'),'url' => ['/site/login']];
    $items2[] = ['label' => Yii::t('app', 'Registration'),'url' => ['/site/register']];
}else{
    if(Yii::$app->user->identity->getIsAdmin()) {
        $items[] = ['label' => Yii::t('app', 'Portfolios'), 'url' => ['/site/portfolios']];
        $items2[] = ['label' => Yii::t('app','Settings'),'items'=>[
            ['label' => Yii::t('app', 'Posts'), 'url' => ['/posts/index']],
            ['label' => Yii::t('app', 'Categories'), 'url' => ['/categories/index']],
            ['label' => Yii::t('app', 'Portfolios'), 'url' => ['/portfolios/index']],
            ['label' => Yii::t('app', 'Tags'), 'url' => ['/tags/index']],

        ]];


    }
    if(!Yii::$app->user->identity->getIsAdmin() && !Yii::$app->user->isGuest){
        $items[] = ['label' => Yii::t('app', 'Portfolios'), 'url' => ['/site/portfolios']];
        $items2[] = ['label' => Yii::t('app','settings'),'items'=>[
            ['label' => Yii::t('app', 'Posts'), 'url' => ['/posts/index']],
        ]];
    }
    $items2[] = ['label' => Yii::t('app', 'Logout'), 'url' => ['/site/logout'], 'linkOptions' => ['data-method' => 'post']];
}
//создание массива---

echo Nav::widget([
    'options' => ['class' => 'navbar-nav affix-top'],
    'items' => $items,
]);

echo Nav::widget([
    'options' => ['class' => 'nav navbar-nav nav_top_rt'],
    'items' => $items2
]);

NavBar::end();
?>

views/layouts/default.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use app\assets\AppAsset;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>

<div class="wrap">
    <?php
    NavBar::begin([
        'brandLabel' => 'My Company',
        'brandUrl' => Yii::$app->homeUrl,
        'options' => [
            'class' => 'navbar-inverse navbar-fixed-top',
        ],
    ]);

    //Создание массива
    $items = [
        ['label' => Yii::t('app', 'Home'), 'url' => ['/']]
    ];
    if(Yii::$app->user->isGuest){
        $items[] = ['label' => Yii::t('app', 'Portfolios'), 'url' => ['/site/portfolios']];
        $items[] = ['label' => Yii::t('app','Login'),'url' => ['/site/login']];
        $items[] = ['label' => Yii::t('app', 'Registration'),'url' => ['/site/register']];
    }else{
        if(Yii::$app->user->identity->getIsAdmin()) {
            $items[] = ['label' => Yii::t('app','settings'),'items'=>[
                ['label' => Yii::t('app', 'Posts'), 'url' => ['/posts/index']],
                ['label' => Yii::t('app', 'Categories'), 'url' => ['/categories/index']],
                ['label' => Yii::t('app', 'Portfolios'), 'url' => ['/portfolios/index']],
                ['label' => Yii::t('app', 'Tags'), 'url' => ['/tags/index']],

            ]];


        }
        if(!Yii::$app->user->identity->getIsAdmin() && !Yii::$app->user->isGuest){
            $items[] = ['label' => Yii::t('app', 'Portfolios'), 'url' => ['/site/portfolios']];
            $items[] = ['label' => Yii::t('app','settings'),'items'=>[
                ['label' => Yii::t('app', 'Posts'), 'url' => ['/posts/index']],
            ]];
        }
        $items[] = ['label' => Yii::t('app', 'LLogout'), 'url' => ['/site/logout'], 'linkOptions' => ['data-method' => 'post']];
    }
    //создание массива---

    echo Nav::widget([
        'options' => ['class' => 'navbar-nav navbar-right'],
        'items' => $items,
    ]);

    NavBar::end();
    ?>

    <div class="container">
        <?= Breadcrumbs::widget([
            'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
        ]) ?>
        <?= $content ?>
    </div>
</div>

<footer class="footer">
    <div class="container">
        <p class="pull-left">&copy; My Company <?= date('Y') ?></p>

        <p class="pull-right"><?= Yii::powered() ?></p>
    </div>
</footer>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>

views/layouts/login.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use yii\helpers\Html;
use app\assets\AppAsset;


AppAsset::register($this);
?>

<?php $this->beginPage() ?>
<!doctype html>
<html lang="<?=Yii::$app->language; ?>">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=<?=Yii::$app->charset; ?>" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
    <link rel="shortcut icon" href="images/favicon.png" type="image/png">
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    <!-- Fav and touch icons -->
</head>
<?php $this->beginBody() ?>
<body class="login" id="page-top">
<!-- LOGIN START
========================================================================= -->
<div class="blue-color full-container text-center">
    <div>
        <div class="col-lg-5 col-md-5 col-sm-5 col-xs-12 login-box"> <a class="logo" href="/"><img alt="logo" src="images/logo.png"></a>
            <?= $content ?>
            <div class="copyright-text"><?=Yii::t('app','My company')?> <?=date('Y')?></div>
            <!--login-box-->
        </div>
    </div>
    <!--blue-color-->
</div>
<!-- /. LOGIN ENDS
    ========================================================================= -->
<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<script src="js/jquery.min.js"></script>
<!-- Include all compiled plugins (below), or include individual files as needed -->
<script src="js/bootstrap/bootstrap.min.js"></script>
</body>
<?=$this->endBody(); ?>
</html>
<?php $this->endPage() ?>

views/layouts/main.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use yii\helpers\Html;
use app\assets\AppAsset;

$js = "
    // FIXED Menu
    jQuery('.navbar').affix({
        offset: {
            top: 1
        }
    });
    
    // tooltip demo
    $(\"[data-toggle=tooltip]\").tooltip();
    
     // popover demo
    $(\"[data-toggle=popover]\")
        .popover()
    ";
$this->registerJs($js,\yii\web\View::POS_READY);

AppAsset::register($this);
?>

<?php $this->beginPage() ?>

<!doctype html>
<html lang="<?=Yii::$app->language; ?>">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=<?=Yii::$app->charset; ?>" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
    <link rel="shortcut icon" href="images/favicon.png" type="image/png">
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    <!-- Fav and touch icons -->
</head>
<body id="page-top">

<?php $this->beginBody() ?>



<div id="loader"></div>

<div id="section-home">
    <header id="header">
        <!-- NAVIGATION STARTS
    ========================================================================= -->
        <nav id="navigation">
            <?=$this->render('_navbar'); ?>
            <div class="navspacer"></div>
        </nav>
        <!-- /. NAVIGATION ENDS
    ========================================================================= -->
    </header>
    <?php if(isset($this->blocks['block1'])): ?>
        <?= $this->blocks['block1']?>
    <?php endif;?>
</div>

<div class="padding-box">
    <div class="container">

                <?= $content ?>
        </div>
    </div>

<div class="padding-box blue-color">
    <div class="container">
        <div class="row header">
            <article class="col-xs-12 social-icons text-center">
                <h2 class="white">Join The 115,000+ Satisfied Users!</h2>
                <ul class="list-inline">
                    <li><a href="#"><span class="fa fa-facebook"></span>facebook</a></li>
                    <li><a href="#"><span class="fa fa-twitter"></span>Twitter</a></li>
                    <li><a href="#"><span class="fa fa-google-plus"></span>Google+</a></li>
                    <li><a href="#"><span class="fa fa-dribbble"></span>Dribble</a></li>
                    <li><a href="#"><span class="fa fa-linkedin"></span>Linkedin</a></li>
                    <li><a href="#"><span class="fa fa-instagram"></span>Instagram</a></li>
                </ul>
                <!--textbox-->
            </article>
            <!--row-->
        </div>
        <!--container-->
    </div>
</div>
<div class="padding-box black2-color">
    <div class="container">
        <div class="row header">
            <aside class="col-sm-4 col-xs-12 small_box"><span class="fa fa-envelope"></span><a href="mailto:hello@designingmedia.com">hello@designingmedia.com</a></aside>
            <aside class="col-sm-5 col-xs-12 small_box"><span class="fa fa-home"></span>121, King Street, Melbourne Victoria 3000</aside>
            <aside class="col-sm-3 col-xs-12 small_box"><span class="fa fa-phone-square"></span>(0800) 234 56789</aside>
            <!--row-->
        </div>
        <!--container-->
    </div>
</div>
<!-- SOCIAL SECTION END

========================================================================= -->
<a class="dmtop" href="#page-top" style="bottom: 25px;"></a>
<!-- FOOTER STARTS
========================================================================= -->

<!-- FOOTER END -->
<?=$this->endBody(); ?>
</body>
</html>
<?php $this->endPage() ?>

views/layouts/reg.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use yii\helpers\Html;
use app\assets\AppAsset;


AppAsset::register($this);
?>

<?php $this->beginPage() ?>
    <!doctype html>
    <html lang="<?=Yii::$app->language; ?>">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=<?=Yii::$app->charset; ?>" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width,initial-scale=1">
        <?= Html::csrfMetaTags() ?>
        <title><?= Html::encode($this->title) ?></title>
        <?php $this->head() ?>
        <link rel="shortcut icon" href="images/favicon.png" type="image/png">
        <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->
        <!-- Fav and touch icons -->
    </head>
    <?php $this->beginBody() ?>
    <body class="login" id="page-top">
    <!-- LOGIN START
    ========================================================================= -->
    <div class="blue-color full-container text-center">
        <div>
            <div class="col-lg-5 col-md-5 col-sm-5 col-xs-12 login-box"> <a class="logo" href="/"><img alt="logo" src="images/logo.png"></a>
                <?= $content ?>
                <div class="copyright-text"><?=Yii::t('app','My company');?> <?= date('Y') ?></div>
                <!--login-box-->
            </div>
        </div>
        <!--blue-color-->
    </div>
    <!-- /. LOGIN ENDS
        ========================================================================= -->
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="js/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="js/bootstrap/bootstrap.min.js"></script>
    </body>
    <?=$this->endBody(); ?>
    </html>
<?php $this->endPage() ?>